# Generated by Django 3.0.3 on 2020-04-22 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchRoutes', '0003_flight_routes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight_Routes',
        ),
    ]
