# Generated by Django 3.0.3 on 2020-04-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searchRoutes', '0004_delete_flight_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=30)),
                ('airline_ID', models.CharField(max_length=30)),
                ('source_airport', models.CharField(max_length=30)),
                ('source_airport_id', models.CharField(max_length=30)),
                ('destination_airport', models.CharField(max_length=30)),
                ('destination_airport_id', models.CharField(max_length=30)),
            ],
        ),
    ]
